const customers = [
  {
    "moc_id": "033423",
    "company_name_en": "Expresso Co ltd",
    "company_name_kh": "អុិចសប្រេសូ",
    "tin": "K001-3333333",
    "date_of_incorporation": null,
    "business_type": null,
    "city": "Phnom Penh",
    "country": "KH",
    "phone_number": "+85544433422",
    "email": "phenpani@gmail.com",
    "step": 1,
    "merchant_name": null,
    "merchant_id": null,
    "bank_name": null,
    "bank_account_number": null,
    "certificate_of_incorporation": 163,
    "certificate_of_tax_registration": 165,
    "bank_acc_ownership_doc": null,
    "authorized_letter": 164,
    "supporting_doc": null,
    "rejected_at": null,
    "national_id": "030551786",
    "description": "Testing",
    "address": "Phnom Penh",
    "status": "APPROVED",
    "onboard_by": "merchant_portal",
    "rejection_type": null,
    "rejection_message": null,
    "is_active": true,
    "created_at": "2024-05-29T04:34:51.912Z",
    "merchant_logo": "https://caminv-stag-merc.mef.gov.kh/buckets/merchant-logo/1716957202994.jpg",
    "logo_id": 162,
    "webhook_url": "https://345f-103-118-47-98.ngrok-free.app/webhook/invoice-received",
    "updated_at": "2024-05-29T04:39:24.894Z",
    "id": "033423",
    "certificate_of_incorporation_file": {
      "id": 163,
      "path": "1716957276541.pdf",
      "original_name": "Business.pdf",
      "size": 4354785
    },
    "certificate_of_tax_registration_file": {
      "id": 165,
      "path": "1716957290952.pdf",
      "original_name": "PA00Z5J5.pdf",
      "size": 30378782
    },
    "authorized_letter_file": {
      "id": 164,
      "path": "1716957283612.pdf",
      "original_name": "Business.pdf",
      "size": 4354785
    }
  },
  {
    "moc_id": "Phaney",
    "company_name_en": "Phaney1",
    "company_name_kh": "Phaney",
    "tin": "Phaney",
    "date_of_incorporation": null,
    "business_type": null,
    "city": "Kampong Speu",
    "country": "KH",
    "phone_number": "+85533322",
    "email": "phenpani@gmail.com",
    "step": 1,
    "merchant_name": null,
    "merchant_id": null,
    "bank_name": null,
    "bank_account_number": null,
    "certificate_of_incorporation": 153,
    "certificate_of_tax_registration": 154,
    "bank_acc_ownership_doc": null,
    "authorized_letter": 155,
    "supporting_doc": null,
    "rejected_at": "2024-05-28T07:49:43.807Z",
    "national_id": "100686476",
    "description": "Phaney",
    "address": "Phaney",
    "status": "APPROVED",
    "onboard_by": "merchant_portal",
    "rejection_type": "Incorrect Business Information",
    "rejection_message": "233",
    "is_active": true,
    "created_at": "2024-05-28T06:54:52.962Z",
    "merchant_logo": "https://caminv-stag-merc.mef.gov.kh/buckets/merchant-logo/1716878667513.png",
    "logo_id": 149,
    "webhook_url": null,
    "updated_at": "2024-05-29T01:49:23.118Z",
    "id": "Phaney",
    "certificate_of_incorporation_file": {
      "id": 153,
      "path": "1716882602553.pdf",
      "original_name": "Business.pdf",
      "size": 4354785
    },
    "certificate_of_tax_registration_file": {
      "id": 154,
      "path": "1716882610115.pdf",
      "original_name": "PA00Z5J5.pdf",
      "size": 30378782
    },
    "authorized_letter_file": {
      "id": 155,
      "path": "1716882612820.pdf",
      "original_name": "1. Khem Darorth.pdf",
      "size": 270584
    }
  },
  {
    "moc_id": "MOC-ABC00001",
    "company_name_en": "ABC",
    "company_name_kh": "កខគ",
    "tin": "TIN000000010",
    "date_of_incorporation": null,
    "business_type": null,
    "city": "Battambang",
    "country": "KH",
    "phone_number": "+85511223344",
    "email": "abc@gmail.com",
    "step": 1,
    "merchant_name": null,
    "merchant_id": null,
    "bank_name": null,
    "bank_account_number": null,
    "certificate_of_incorporation": 127,
    "certificate_of_tax_registration": 124,
    "bank_acc_ownership_doc": null,
    "authorized_letter": 126,
    "supporting_doc": null,
    "rejected_at": null,
    "national_id": "011223344",
    "description": "test",
    "address": "abc abc",
    "status": "APPROVED",
    "onboard_by": "admin_portal",
    "rejection_type": null,
    "rejection_message": null,
    "is_active": true,
    "created_at": "2024-05-23T01:35:02.803Z",
    "merchant_logo": "https://caminv-stag-merc.mef.gov.kh/buckets/merchant-logo/1716427632733.jpg",
    "logo_id": 123,
    "webhook_url": null,
    "updated_at": "2024-05-23T02:04:14.677Z",
    "id": "MOC-ABC00001"
  },
  {
    "moc_id": "333333",
    "company_name_en": "Phaney",
    "company_name_kh": "Phin",
    "tin": "3333",
    "date_of_incorporation": null,
    "business_type": null,
    "city": "Kampot",
    "country": "KH",
    "phone_number": "+855334333",
    "email": "phenpani@gmail.com",
    "step": 1,
    "merchant_name": null,
    "merchant_id": null,
    "bank_name": null,
    "bank_account_number": null,
    "certificate_of_incorporation": 90,
    "certificate_of_tax_registration": 91,
    "bank_acc_ownership_doc": null,
    "authorized_letter": 92,
    "supporting_doc": null,
    "rejected_at": null,
    "national_id": "0305517861",
    "description": "333",
    "address": "33",
    "status": "APPROVED",
    "onboard_by": "merchant_portal",
    "rejection_type": null,
    "rejection_message": null,
    "is_active": true,
    "created_at": "2024-04-05T02:08:40.234Z",
    "merchant_logo": "https://caminv-stag-merc.mef.gov.kh/buckets/merchant-logo/1715933008809.jpg",
    "logo_id": 117,
    "webhook_url": null,
    "updated_at": "2024-05-17T08:03:43.026Z",
    "id": "333333"
  },
  {
    "moc_id": "testing",
    "company_name_en": "testing",
    "company_name_kh": "testing",
    "tin": "testing",
    "date_of_incorporation": null,
    "business_type": null,
    "city": "Kampong Cham",
    "country": "KH",
    "phone_number": "+855333223322243",
    "email": "phenpani@gmail.com",
    "step": 1,
    "merchant_name": null,
    "merchant_id": null,
    "bank_name": null,
    "bank_account_number": null,
    "certificate_of_incorporation": 25,
    "certificate_of_tax_registration": 26,
    "bank_acc_ownership_doc": null,
    "authorized_letter": 27,
    "supporting_doc": null,
    "rejected_at": null,
    "national_id": "2333322222",
    "description": "item2",
    "address": "item3",
    "status": "APPROVED",
    "onboard_by": "admin_portal",
    "rejection_type": null,
    "rejection_message": null,
    "is_active": true,
    "created_at": "2024-03-25T02:15:04.772Z",
    "merchant_logo": null,
    "logo_id": null,
    "webhook_url": null,
    "updated_at": "2024-03-25T02:15:04.772Z",
    "id": "testing"
  },
  {
    "moc_id": "233333233",
    "company_name_en": "TEsting",
    "company_name_kh": "TEsting",
    "tin": "3334333",
    "date_of_incorporation": null,
    "business_type": null,
    "city": "Kampot",
    "country": "KH",
    "phone_number": "+855332245334",
    "email": "phenpani@gmail.com",
    "step": 1,
    "merchant_name": null,
    "merchant_id": null,
    "bank_name": null,
    "bank_account_number": null,
    "certificate_of_incorporation": 28,
    "certificate_of_tax_registration": 29,
    "bank_acc_ownership_doc": null,
    "authorized_letter": 30,
    "supporting_doc": null,
    "rejected_at": null,
    "national_id": "334433",
    "description": "33443",
    "address": "333",
    "status": "APPROVED",
    "onboard_by": "admin_portal",
    "rejection_type": null,
    "rejection_message": null,
    "is_active": true,
    "created_at": "2024-03-27T03:17:36.803Z",
    "merchant_logo": null,
    "logo_id": null,
    "webhook_url": null,
    "updated_at": "2024-03-27T03:17:36.803Z",
    "id": "233333233"
  },
  {
    "moc_id": "1010016182",
    "company_name_en": "JAICODE CO., LTD.",
    "company_name_kh": "ចៃកូដ ឯ.ក",
    "tin": "K008-902300031",
    "date_of_incorporation": "2024-03-03T17:00:00.000Z",
    "business_type": "Private Limited Company",
    "city": "Phnom Penh",
    "country": "KH",
    "phone_number": "+85512334455",
    "email": "panha@mail.com",
    "step": 3,
    "merchant_name": "abc",
    "merchant_id": "123",
    "bank_name": "ABA",
    "bank_account_number": "678",
    "certificate_of_incorporation": 19,
    "certificate_of_tax_registration": 18,
    "bank_acc_ownership_doc": 20,
    "authorized_letter": 21,
    "supporting_doc": 22,
    "rejected_at": null,
    "national_id": "011137214",
    "description": "Testing purpose",
    "address": "#2ba st.656",
    "status": "APPROVED",
    "onboard_by": "merchant_portal",
    "rejection_type": null,
    "rejection_message": null,
    "is_active": true,
    "created_at": "2024-03-04T10:11:34.086Z",
    "merchant_logo": "https://caminv-stag-merc.mef.gov.kh/buckets/merchant-logo/1713769827935.jpg",
    "logo_id": 95,
    "webhook_url": null,
    "updated_at": "2024-04-22T07:10:28.069Z",
    "id": "1010016182"
  }
]
  
export default customers